//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliodeJeux
{
    using System;
    using System.Collections.Generic;
    
    public partial class jeux
    {
        public int id { get; set; }
        public string titre { get; set; }
        public string contenu { get; set; }
        public string règle { get; set; }
        public string condit { get; set; }
        public string nombre_joueurs { get; set; }
        public string nombre_cartes { get; set; }
    }
}
